project:
  type: website

website:
  title: "ISSS626-GAA"
  navbar:
    left:
     - text: "Hands-on Exercise 1"
       menu: 
         - text: "Hands-on Exercise 1.1"
           href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex1.1.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: pulse
    css: styles.css
    toc: true

editor: visual

